SELECT * FROM customer_behaviour;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer_behaviour
GROUP BY gender
ORDER BY revenue DESC;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM customer_behaviour.customer_behaviour
WHERE discount_applied = 'Yes'
AND purchase_amount > (
        SELECT AVG(purchase_amount)
        FROM customer_behaviour.customer_behaviour
);


-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating),2) 
AS avg_product_rating
FROM customer_behaviour.customer_behaviour
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customer_behaviour.customer_behaviour
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       SUM(purchase_amount) AS total_revenue
FROM customer_behaviour.customer_behaviour
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) 
AS discount_percentage
FROM customer_behaviour.customer_behaviour
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM (SELECT customer_id,
			CASE
			WHEN previous_purchases = 0 THEN 'New'
			WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
			ELSE 'Loyal'
			END AS customer_segment
        FROM customer_behaviour.customer_behaviour
     ) AS segmented_customers
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
SELECT category, item_purchased, total_orders
FROM (
        SELECT category, item_purchased,
               COUNT(*) AS total_orders,
               ROW_NUMBER() OVER(
                    PARTITION BY category
                    ORDER BY COUNT(*) DESC
               ) AS rank_num
        FROM customer_behaviour.customer_behaviour
        GROUP BY category, item_purchased
     ) ranked_products
WHERE rank_num <= 3;
 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_behaviour.customer_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_behaviour.customer_behaviour
GROUP BY age_group
ORDER BY total_revenue DESC;
